### ISSUE TITLE
READMEのUsageの修正

### ISSUE THREAD

**Issue by p1atdev** [shibata-kuronosuke/Withreate-demo#1]
`npm install` を挟まないと `npm run dev` できない
(ちょっと細かいかもしれないけど)

**Comment by p1atdev** [comment]
`node_modules` は `.gitignore` に追加した方がいい気がするけどプロトタイプだし別にいいかっていう気もする

**Comment by shibata-kuronosuke** [comment]
修正しました
ありがとうございます！
